# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: riteshschaudhari19
# "service" is the name of this project. This will also be added to your AWS resource names.
service: serverless3

provider:
  name: aws
  runtime: nodejs20.x

functions:
  helloFn:
    handler: handler.hello
    events:
      - httpApi:
          path: /hello
          method: get
